name: R-CMD-check
on:
  workflow_dispatch:
  push:
    paths: ["om/R/**"]

permissions:
  contents: write

jobs:
  simple-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
          
      - name: Setup
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: om
          extra-packages: any::rcmdcheck
          needs: check

      - name: Check
        uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: om
          
      

