name: R-CMD-check
on:
  workflow_dispatch:
  push:
    paths: ["om/R/**"]
    
permissions:
  contents: write

jobs:
  simple-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - name: Checkout 
        uses: actions/checkout@v7
        with:
          repository: protected-species-management/operating-model
          path: om
    
      - name: LaTeX
        uses: r-lib/actions/setup-tinytex@v2
      
      - name: Setup
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Boost Headers
        run:  sudo apt update -y && sudo apt install -y libboost-all-dev

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: operating-model/om
          extra-packages: |
            any::TMB
            any::RTMB
            any::roxygen2
            any::BH
            any::Rcpp
            any::RcppEigen
          needs: |
            check
            roxygen2
        
      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}
        
      - name: Commit and push document changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add om/man/\* NAMESPACE DESCRIPTION
          git commit -m "Update documentation" || echo "No changes to commit"
          git pull
          git push

      - name: Simple check
        uses: r-lib/actions/check-r-package@v2

          
