name: R-CMD-check
on:
  workflow_dispatch:
  push:
    paths: ["om/R/**"]

permissions:
  contents: write

jobs:
  simple-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: protected-species-management/operating-model
          path: om
          
      - name: Setup
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          working-directory: om
          
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: om
          packages: deps::om
          extra-packages: |
            any::rcmdcheck
            any::TMB
          needs: |
            check

      - name: Check
        run: rcmdcheck::rcmdcheck("om")
        shell: Rscript {0}
          
      

